name: Manual Hello Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, ${{ github.actor }}!"
